### ISSUE TITLE
[Bug]: Handle exception when same failed upload twice

### ISSUE THREAD

**Issue by Aisuko** [SkywardAI/chat-backend#81]
```
backend_app    | (sqlalchemy.dialects.postgresql.asyncpg.IntegrityError) <class 'asyncpg.exceptions.UniqueViolationError'>: duplicate key value violates unique constraint "uploaded_file_name_key"
backend_app    | DETAIL:  Key (name)=(Sample.csv) already exists.
backend_app    | [SQL: INSERT INTO uploaded_file (name) VALUES ($1::VARCHAR) RETURNING uploaded_file.id]
backend_app    | [parameters: ('Sample.csv',)]
backend_app    | (Background on this error at: https://sqlalche.me/e/20/gkpj)
backend_app    | INFO:     38.150.15.131:44526 - "POST /api/file HTTP/1.1" 500 Internal Server Error
backend_app    | ERROR:    Exception in ASGI application
backend_app    | Traceback (most recent call last):
backend_app    |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 538, in _prepare_and_execute
backend_app    |     self._rows = await prepared_stmt.fetch(*parameters)
backend_app    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend_app    |   File "/usr/local/lib/python3.11/site-packages/asyncpg/prepared_stmt.py", line 176, in fetch
backend_app    |     data = await self.__bind_execute(args, 0, timeout)
backend_app    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend_app    |   File "/usr/local/lib/python3.11/site-packages/asyncpg/prepared_stmt.py", line 241, in __bind_execute
backend_app    |     data, status, _ = await self.__do_execute(
backend_app    |                       ^^^^^^^^^^^^^^^^^^^^^^^^
backend_app    |   File "/usr/local/lib/python3.11/site-packages/asyncpg/prepared_stmt.py", line 230, in __do_execute
backend_app    |     return await executor(protocol)
backend_app    |            ^^^^^^^^^^^^^^^^^^^^^^^^
backend_app    |   File "asyncpg/protocol/protocol.pyx", line 207, in bind_execute
backend_app    | asyncpg.exceptions.UniqueViolationError: duplicate key value violates unique constraint "uploaded_file_name_key"
backend_app    | DETAIL:  Key (name)=(Sample.csv) already exists.
backend_app    | 
backend_app    | The above exception was the direct cause of the following exception:
backend_app    | 
backend_app    | Traceback (most recent call last):
backend_app    |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1971, in _exec_single_context
backend_app    |     self.dialect.do_execute(
backend_app    |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 919, in do_execute
backend_app    |     cursor.execute(statement, parameters)
backend_app    |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 572, in execute
backend_app    |     self._adapt_connection.await_(
backend_app    |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 131, in await_only
backend_app    |     return current.driver.switch(awaitable)  # type: ignore[no-any-return]
backend_app    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend_app    |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 196, in greenlet_spawn
backend_app    |     value = await result
backend_app    |             ^^^^^^^^^^^^
backend_app    |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 550, in _prepare_and_execute
backend_app    |     self._handle_exception(error)
backend_app    |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 501, in _handle_exception
backend_app    |     self._adapt_connection._handle_exception(error)
backend_app    |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 789, in _handle_exception
backend_app    |     raise translated_error from error
backend_app    | sqlalchemy.dialects.postgresql.asyncpg.AsyncAdapt_asyncpg_dbapi.IntegrityError: <class 'asyncpg.exceptions.UniqueViolationError'>: duplicate key value violates unique constraint "uploaded_file_name_key"
backend_app    | DETAIL:  Key (name)=(Sample.csv) already exists.
backend_app    | 
backend_app    | The above exception was the direct cause of the following exception:
backend_app    | 
backend_app    | Traceback (most recent call last):
backend_app    |   File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
backend_app    |     result = await app(  # type: ignore[func-returns-value]
backend_app    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend_app    |   File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
backend_app    |     return await self.app(scope, receive, send)
backend_app    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend_app    |   File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
backend_app    |     await super().__call__(scope, receive, send)
backend_app    |   File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
backend_app    |     await self.middleware_stack(scope, receive, send)
backend_app    |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
backend_app    |     raise exc
backend_app    |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
backend_app    |     await self.app(scope, receive, _send)
backend_app    |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 91, in __call__
backend_app    |     await self.simple_response(scope, receive, send, request_headers=headers)
backend_app    |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 146, in simple_response
backend_app    |     await self.app(scope, receive, send)
backend_app    |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
backend_app    |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
backend_app    |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
backend_app    |     raise exc
backend_app    |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
backend_app    |     await app(scope, receive, sender)
backend_app    |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 758, in __call__
backend_app    |     await self.middleware_stack(scope, receive, send)
backend_app    |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 778, in app
backend_app    |     await route.handle(scope, receive, send)
backend_app    |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 299, in handle
backend_app    |     await self.app(scope, receive, send)
backend_app    |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 79, in app
backend_app    |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
backend_app    |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
backend_app    |     raise exc
backend_app    |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
backend_app    |     await app(scope, receive, sender)
backend_app    |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 74, in app
backend_app    |     response = await func(request)
backend_app    |                ^^^^^^^^^^^^^^^^^^^
backend_app    |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 278, in app
backend_app    |     raw_response = await run_endpoint_function(
backend_app    |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend_app    |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
backend_app    |     return await dependant.call(**values)
backend_app    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend_app    |   File "/app/src/api/routes/file.py", line 32, in upload_and_return_id
backend_app    |     new_file = await file_repo.create_uploadfile(file_name=file.filename)
backend_app    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend_app    |   File "/app/src/repository/crud/file.py", line 17, in create_uploadfile
backend_app    |     await self.async_session.commit()
backend_app    |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/ext/asyncio/session.py", line 1009, in commit
backend_app    |     await greenlet_spawn(self.sync_session.commit)
backend_app    |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 203, in greenlet_spawn
backend_app    |     result = context.switch(value)
backend_app    |              ^^^^^^^^^^^^^^^^^^^^^
backend_app    |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1972, in commit
backend_app    |     trans.commit(_to_root=True)
backend_app    |   File "<string>", line 2, in commit
backend_app    |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
backend_app    |     ret_value = fn(self, *arg, **kw)
backend_app    |                 ^^^^^^^^^^^^^^^^^^^^
backend_app    |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1257, in commit
backend_app    |     self._prepare_impl()
backend_app    |   File "<string>", line 2, in _prepare_impl
backend_app    |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
backend_app    |     ret_value = fn(self, *arg, **kw)
backend_app    |                 ^^^^^^^^^^^^^^^^^^^^
backend_app    |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1232, in _prepare_impl
backend_app    |     self.session.flush()
backend_app    |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 4296, in flush
backend_app    |     self._flush(objects)
backend_app    |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 4431, in _flush
backend_app    |     with util.safe_reraise():
backend_app    |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
backend_app    |     raise exc_value.with_traceback(exc_tb)
backend_app    |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 4392, in _flush
backend_app    |     flush_context.execute()
backend_app    |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
backend_app    |     rec.execute(self)
backend_app    |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
backend_app    |     util.preloaded.orm_persistence.save_obj(
backend_app    |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
backend_app    |     _emit_insert_statements(
backend_app    |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/persistence.py", line 1233, in _emit_insert_statements
backend_app    |     result = connection.execute(
backend_app    |              ^^^^^^^^^^^^^^^^^^^
backend_app    |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1422, in execute
backend_app    |     return meth(
backend_app    |            ^^^^^
backend_app    |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/sql/elements.py", line 514, in _execute_on_connection
backend_app    |     return connection._execute_clauseelement(
backend_app    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend_app    |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1644, in _execute_clauseelement
backend_app    |     ret = self._execute_context(
backend_app    |           ^^^^^^^^^^^^^^^^^^^^^^
backend_app    |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1850, in _execute_context
backend_app    |     return self._exec_single_context(
backend_app    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
backend_app    |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1990, in _exec_single_context
backend_app    |     self._handle_dbapi_exception(
backend_app    |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2357, in _handle_dbapi_exception
backend_app    |     raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
backend_app    |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1971, in _exec_single_context
backend_app    |     self.dialect.do_execute(
backend_app    |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 919, in do_execute
backend_app    |     cursor.execute(statement, parameters)
backend_app    |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 572, in execute
backend_app    |     self._adapt_connection.await_(
backend_app    |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 131, in await_only
backend_app    |     return current.driver.switch(awaitable)  # type: ignore[no-any-return]
backend_app    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend_app    |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 196, in greenlet_spawn
backend_app    |     value = await result
backend_app    |             ^^^^^^^^^^^^
backend_app    |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 550, in _prepare_and_execute
backend_app    |     self._handle_exception(error)
backend_app    |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 501, in _handle_exception
backend_app    |     self._adapt_connection._handle_exception(error)
backend_app    |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 789, in _handle_exception
backend_app    |     raise translated_error from error
backend_app    | sqlalchemy.exc.IntegrityError: (sqlalchemy.dialects.postgresql.asyncpg.IntegrityError) <class 'asyncpg.exceptions.UniqueViolationError'>: duplicate key value violates unique constraint "uploaded_file_name_key"
backend_app    | DETAIL:  Key (name)=(Sample.csv) already exists.
backend_app    | [SQL: INSERT INTO uploaded_file (name) VALUES ($1::VARCHAR) RETURNING uploaded_file.id]
```

**Comment by jinronga** [comment]
This bug causes database insertion errors due to existing file names. Can we return a 'file name already exists' exception to the frontend, similar to checking email or username?
![image](https://github.com/SkywardAI/chat-backend/assets/52482860/8dc0875d-47d3-4941-be5a-a99fc61ffb58)

**Comment by Micost** [comment]
Close per PR#86 fixed
